adventure/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('game/', include('game.urls')),
    path('admin/', admin.site.urls),
]

game/urls.py
from django.urls import path

from . import views

app_name = 'game'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:situation_id>/', views.detail, name='detail'),
    path('<int:situation_id>/choose/', views.choose, name='choose'),
]

game/models.py
from django.db import models

class Situation(models.Model):
    title = models.CharField(max_length=100)
    situation_text = models.TextField()

    def __str__(self):
        return self.title


class Choice(models.Model):
    situation = models.ForeignKey(Situation, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    next_situation = models.ForeignKey(Situation, on_delete=models.CASCADE, related_name='+')

    def __str__(self):
        return self.choice_text

game/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Situation, Choice


def index(request):
    return detail(request, 1)

def detail(request, situation_id):
    situation = get_object_or_404(Situation, id=situation_id)
    return render(request, 'game/detail.html', { 'situation': situation, })

def choose(request, situation_id):
    situation = get_object_or_404(Situation, id=situation_id)
    try:
        selected_choice = situation.choice_set.get(id=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'game/detail.html', {
            'situation': situation,
            'error_message': "You didn't select a choice.",
        })
    else:
        return HttpResponseRedirect(reverse('game:detail', args=(selected_choice.next_situation.id,)))

game/templates/game/base.html
<!doctype html>
<html>
  <head>
      <meta charset="utf-8">
      <title>Adventure</title>
  </head>
  <body>
      <h1>Text Adventure</h1>
      {% block content %}{% endblock %}
  </body>
</html>

game/templates/game/choices.html
<form action="{% url 'game:choose' situation.id %}" method="post">
  {% csrf_token %}
  {% for choice in situation.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
  <input type="submit" value="Submit" />
</form>

game/templates/game/detail.html
{% extends "game/base.html" %}

{% block content %}
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <div><p>{{ situation.situation_text }}</p></div>
  {% if situation.choice_set.all.count > 0 %}
    {% include "game/choices.html" with situation=situation %}
  {% else %}
    {% include "game/restart.html" %}
  {% endif %}
{% endblock content %}

game/templates/game/restart.html
<form action="{% url 'game:index' %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Restart" />
</form>